export const ENDPOINTS = {
    CLUB: 'club',
    CHARACTERISTIC: 'characteristic',
    PLAYINGFIELD: 'playingField',
    ADDRESS: 'address',
    RECOMMENDED: 'club/recommended',
    RANDOM: 'club/random',
    IMAGES: 'image/club',
    SPORT: 'sport',
    CITY: 'city',
    CATEGORY: 'category',
    CLUB_BY_CATEGORY: 'club/by-categories',
    USER:'user',
    USER_CREATE: 'user/signup',
    USER_SIGN_IN: 'login',
    EMAIL_CONFIRM: 'email/sendMessage',
    FAVORITES: 'favorites',
    RESERVATIONS_BY_CLUB: 'reservation/searchByClub',
    RESERVATION: 'reservation',
    CLUB_SEARCH: 'club/search'
}